/**
 * @description class implementing the iActionable interface to create controls. 
 */
public with sharing class ControlActionable implements iActionable {
	
	/**
	 * @description method to add parameters to be used in the creator.
	 * @param key for the parameter
	 * @param the value
	 */
	public void addParam(String key, Object value) {
		
	}
	
	/**
	 * @description perform the action
	 * @param  execution context containing the Id for action record incase it's needed
	 */
	public void execute(ExecutionContext executionContext){

	}
}
